name: ColorMC构建

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:        
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        token: ${{ secrets.KEY1 }}

    - name: 设置.NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.300

    - name: Read version number
      id: version
      run: |
        VERSION=$(cat ./build/version)
        echo "VERSION=$VERSION" >> $GITHUB_ENV  
        MAINVERSION=$(cat ./build/main_version)
        echo "MAINVERSION=$MAINVERSION" >> $GITHUB_ENV  

    # - name: 更新源码
    #   shell: bash
    #   working-directory: ./
    #   run: |
    #     chmod a+x ./build/update.sh
    #     ./build/update.sh

    - name: 构建源码
      shell: bash
      working-directory: ./
      run: |
        chmod a+x ./build/build-linux.sh
        ./build/build-linux.sh

    - name: 构建 deb
      shell: bash
      working-directory: ./
      run: |
        chmod a+x ./build/build-ubuntu.sh
        ./build/build-ubuntu.sh

    - name: 构建 rpm
      shell: bash
      working-directory: ./
      run: |
        chmod a+x ./build/build-rpm.sh
        ./build/build-rpm.sh

    - name: 构建 pkg
      run: |
        docker run --name build-container -v "${{ github.workspace }}:/github/workspace" archlinux:latest /bin/bash -c "\
        pacman -Syu --noconfirm base-devel git && \
        useradd -m builder && \
        cd /github/workspace && \
        chown -R builder:builder /github/workspace/ && \
        chmod -R 777 /github/workspace/ && \
        echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder && \
        sudo -u builder ./build/build-arch.sh"

    - name: 上传 colormc-linux-x86_64-rpm
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-x86_64-rpm"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-1.x86_64.rpm

    - name: 上传 colormc-linux-aot-x86_64-rpm
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-aot-x86_64-rpm"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-1-aot.x86_64.rpm
    
    - name: 上传 colormc-linux-min-x86_64-rpm
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-min-x86_64-rpm"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-1-min.x86_64.rpm

    - name: 上传 colormc-linux-aarch64-rpm
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-aarch64-rpm"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-1.aarch64.rpm

    # - name: 上传 colormc-linux-aot-aarch64-rpm
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: "colormc-linux-aot-aarch64-rpm"
    #     path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-1-aot.aarch64.rpm

    - name: 上传 colormc-linux-min-aarch64-rpm
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-min-aarch64-rpm"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-1-min.aarch64.rpm

    - name: 上传 colormc-linux-x86_64-pkg
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-x86_64-pkg"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-1-x86_64.pkg.tar.zst

    - name: 上传 colormc-linux-min-x86_64-pkg
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-min-x86_64-pkg"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-1-min-x86_64.pkg.tar.zst

    - name: 上传 colormc-linux-aot-x86_64-pkg
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-aot-x86_64-pkg"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-1-aot-x86_64.pkg.tar.zst

    - name: 上传 colormc-linux-amd64-deb
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-amd64-deb"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-amd64.deb

    - name: 上传 colormc-linux-aot-amd64-deb
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-aot-amd64-deb"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-aot-amd64.deb

    - name: 上传 colormc-linux-min-amd64-deb
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-min-amd64-deb"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-min-amd64.deb

    - name: 上传 colormc-linux-aarch64-deb
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-aarch64-deb"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-arm64.deb

    # - name: 上传 colormc-linux-aot-aarch64-deb
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: "colormc-linux-aot-aarch64-deb"
    #     path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-aot-arm64.deb

    - name: 上传 colormc-linux-min-aarch64-deb
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-min-aarch64-deb"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-min-arm64.deb
    
    - name: 上传 linux-x64-appimage.deb
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-x86_64-appimage"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-x86_64.AppImage

    - name: 上传 colormc-linux-aot-x86_64-appimage
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-aot-x86_64-appimage"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-aot-x86_64.AppImage

    - name: 上传 colormc-linux-min-x86_64-appimage
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-linux-min-x86_64-appimage"
        path: build_out/colormc-linux-${{ env.MAINVERSION }}${{ env.VERSION }}-min-x86_64.AppImage

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        token: ${{ secrets.KEY1 }}

    - name: 设置.NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.300

    - name: Read version number
      id: version
      run: |
        VERSION=$(cat ./build/version)
        echo "VERSION=$VERSION" >> $GITHUB_ENV  
        MAINVERSION=$(cat ./build/main_version)
        echo "MAINVERSION=$MAINVERSION" >> $GITHUB_ENV  

    # - name: 更新源码
    #   shell: bash
    #   working-directory: ./
    #   run: |
    #     chmod a+x ./build/update.sh
    #     ./build/update.sh

    - name: 构建
      shell: bash
      working-directory: ./
      run: |
        chmod a+x ./build/build-macos.sh
        ./build/build-macos.sh

    - name: 上传 colormc-macos-x86_64
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-macos-x86_64"
        path: build_out/colormc-macos-${{ env.MAINVERSION }}${{ env.VERSION }}-x86_64.zip

    - name: 上传 colormc-macos-min-x86_64
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-macos-min-x86_64"
        path: build_out/colormc-macos-${{ env.MAINVERSION }}${{ env.VERSION }}-min-x86_64.zip

    - name: 上传 colormc-macos-aarch64
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-macos-aarch64"
        path: build_out/colormc-macos-${{ env.MAINVERSION }}${{ env.VERSION }}-aarch64.zip

    - name: 上传 colormc-macos-min-aarch64
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-macos-min-aarch64"
        path: build_out/colormc-macos-${{ env.MAINVERSION }}${{ env.VERSION }}-min-aarch64.zip

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        token: ${{ secrets.KEY1 }}

    - name: Read version number
      id: version
      run: |
        $version = Get-Content ./build/version
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        $mainversion = Get-Content ./build/main_version
        echo "MAINVERSION=$mainversion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: 设置.NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.300

    # - name: 更新源码
    #   shell: cmd
    #   working-directory: ./
    #   run: ./build/update.cmd

    - name: 构建 源码
      shell: cmd
      working-directory: ./
      run: ./build/build-windows.cmd
    
    - name: Build MSI with MSBuild
      working-directory: ./
      run: ./build/build-msi.cmd

    - name: 上传 colormc-windows-x64-msi
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-windows-x64-msi"
        path: src/ColorMC.Setup.Wix/colormc-windows-${{ env.MAINVERSION }}${{ env.VERSION }}-x64.msi

    - name: 上传 colormc-windows-x64-aot-msi
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-windows-x64-aot-msi"
        path: src/ColorMC.Setup.Wix/colormc-windows-${{ env.MAINVERSION }}${{ env.VERSION }}-aot-x64.msi

    - name: 上传 colormc-windows-x64-min-msi
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-windows-x64-min-msi"
        path: src/ColorMC.Setup.Wix/colormc-windows-${{ env.MAINVERSION }}${{ env.VERSION }}-min-x64.msi

    - name: 上传 colormc-windows-x86_64
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-windows-x86_64"
        path: src/build_out/win-x64-dotnet/colormc/**
    
    - name: 上传 colormc-windows-aot-x86_64
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-windows-aot-x86_64"
        path: src/build_out/win-x64-aot/colormc/**

    - name: 上传 colormc-windows-min-x86_64
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-windows-min-x86_64"
        path: src/build_out/win-x64-min/colormc/**

    - name: 上传 colormc-windows-x86
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-windows-x86"
        path: src/build_out/win-x86-dotnet/colormc/**

    - name: 上传 colormc-windows-arm64
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-windows-arm64"
        path: src/build_out/win-arm64-dotnet/colormc/**

    - name: 上传 colormc-windows-aot-arm64
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-windows-aot-arm64"
        path: src/build_out/win-arm64-aot/colormc/**

    - name: 上传 colormc-windows-min-arm64
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-windows-min-arm64"
        path: src/build_out/win-arm64-min/colormc/**