name: ColorMC构建

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:        
      - '*'

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 设置.NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.100

    - name: 更新源码
      shell: bash
      working-directory: ./
      run: |
        chmod a+x ./build/update.sh
        ./build/update.sh

    - name: 构建
      shell: bash
      working-directory: ./
      run: |
        chmod a+x ./build/build-ubuntu.sh
        ./build/build-ubuntu.sh

    - name: 上传 ZIP
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-ubuntu"
        path: build_out/

  build-macos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: 设置.NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.100

    - name: 更新源码
      shell: bash
      working-directory: ./
      run: |
        chmod a+x ./build/update.sh
        ./build/update.sh

    - name: 构建
      shell: bash
      working-directory: ./
      run: |
        chmod a+x ./build/build-macos.sh
        ./build/build-macos.sh

    - name: 上传 ZIP
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-macos"
        path: build_out/

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: 设置.NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.100

    - name: 更新源码
      shell: cmd
      working-directory: ./
      run: ./build/update.cmd

    - name: 构建
      shell: cmd
      working-directory: ./
      run: ./build/build-windows.cmd

    - name: 上传 ZIP
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-windows"
        path: build_out/

  build-arch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 更新源码
      shell: bash
      working-directory: ./
      run: |
        chmod a+x ./build/update.sh
        ./build/update.sh

    - name: 构建
      run: |
        docker run --name build-container -v "${{ github.workspace }}:/github/workspace" archlinux:latest /bin/bash -c "\
        pacman -Syu --noconfirm base-devel git && \
        pacman -Sy --noconfirm dotnet-sdk-8.0 && \
        # 创建一个普通用户 'builder'
        useradd -m builder && \
        # 给 'builder' 用户 sudo 权限
        echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder && \
        # 切换到 'builder' 用户并运行构建脚本
        su -c 'cd /github/workspace && chmod a+x ./build/build-arch.sh && ./build/build-arch.sh' builder"

    - name: 上传 ZIP
      uses: actions/upload-artifact@v4
      with:
        name: "colormc-arch"
        path: build_out/